spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
    username: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/api/certs
server:
  port: 8081

user:
  user-uri: http://localhost:8080/api/users/

hazelcast:
  url: localhost:5701