spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URI}:${DATASOURCE_PORT}/${DATASOURCE_DB}
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${USERS_URI}/api/certs
server:
  port: 8081

user:
  user-uri: http://User-app/api/users/

hazelcast:
  url: ${HAZELCAST_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka/

myapp:
  bootstrap-servers: ${KAFKA_URI}
  topics:
    groupId: order-group
    name: someTopic